### ISSUE TITLE
twython.exceptions.TwythonAuthError: Unable to obtain OAuth 2 access token.

### ISSUE THREAD

**Issue by fibears** [maxcw/time-maps#1]
I meet a question.

I get this error message:
 `twython.exceptions.TwythonAuthError: Unable to obtain OAuth 2 access token.`

I paste the credentials into the function of "my_secrets()".

My code is:

```
`def my_secrets(): # store your twitter codes
d={}
d['APP_KEY'] = "CGlSUYxxxx"
d['APP_SECRET'] = "szRQH2xxxx"
d['my_access_token_key'] = "287224990-xxxx"
d['my_access_token_secret'] = "qzexFFxxxxx"
return d`
```

p.s. 
What's wrong with my code?
Thanks.

**Comment by maxcw** [comment]
I'm not sure. Here's one idea. In the function twitter_auth2(), replace
twitter = Twython(APP_KEY, APP_SECRET,oauth_version=2) 
with:
twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)

The first line works for me, but I'm using Twython 3.2. Maybe if you have a newer version, the second line will work.

I got this from:

https://twython.readthedocs.org/en/latest/usage/starting_out.html

Let me know if that works!

**Comment by maxcw** [comment]
Nevermind. That's a mistake. I would just try following the steps in the Twython setup:
https://twython.readthedocs.org/en/latest/usage/starting_out.html#use-the-access-token
and try to gain more insight that way.

**Comment by fibears** [comment]
Sorry. I don't know what you mean.

The variable  ACCESS_TOKEN came from "twitter"( `ACCESS_TOKEN = twitter.obtain_access_token()`)

So if I replace the code what you mentioned, there may exist some problem?

```
`def twitter_auth2(): # for Twython authentication

secrets=my_secrets()

APP_KEY=secrets['APP_KEY']
APP_SECRET=secrets['APP_SECRET']
my_access_token_key=secrets['my_access_token_key']
my_access_token_secret=secrets['my_access_token_secret']

twitter = Twython(APP_KEY, APP_SECRET,oauth_version=2)
ACCESS_TOKEN = twitter.obtain_access_token()
twitter = Twython(APP_KEY,access_token=ACCESS_TOKEN)

return twitter`
```

Thanks.

**Comment by maxcw** [comment]
The replacement I suggested was a mistake. Before using my code, just try following the steps on the Twython website for OAuth 2:

https://twython.readthedocs.org/en/latest/usage/starting_out.html

And see if you can do that successfully. If you can't, then I'm not sure what's wrong, since it involves the Twython authentication itself, not my program.

**Comment by fibears** [comment]
OK. 

Thank you. Let me try.

**Comment by maxcw** [comment]
Since no one else has mentioned this problem, I'll close this issue.
